package review

import (
	"context"
	"strings"
	"testing"

	"github.com/jdziat/open-nitpick/internal/config"
	"github.com/jdziat/open-nitpick/internal/diff"
	"github.com/jdziat/open-nitpick/internal/prflow"
	"github.com/jdziat/open-nitpick/internal/vcs"
)

// TestReviewPublishesFlowFromTheCompleteDiff guards the ordering contract:
// flow precedes incremental narrowing and reaches the normal review body
// without changing the outcome of model review.
func TestReviewPublishesFlowFromTheCompleteDiff(t *testing.T) {
	provider := &stubProvider{
		diff: engineDiff,
		content: map[string]string{"app.go": `package app
func Get() { helper() }
func helper() {}
`},
	}
	model := &scriptedLLM{fallback: `{"findings":[]}`}
	engine := newEngine(t, model, provider, func(cfg *config.Config) {
		cfg.Flow.Mode = config.FlowOn
		cfg.Review.Summary = false
	})

	report, err := engine.Review(context.Background(), vcs.Ref{})
	if err != nil {
		t.Fatalf("Review: %v", err)
	}
	for _, want := range []string{"## Application flows (static analysis)", "Status: **partial**", "base_source_unavailable", "```mermaid", "app&#46;Get", "app&#46;helper"} {
		if !strings.Contains(report.FlowMarkdown, want) {
			t.Errorf("flow output missing %q:\n%s", want, report.FlowMarkdown)
		}
	}
	if !report.PipelineComplete() {
		t.Fatalf("flow status altered review completeness: %+v", report)
	}
	if strings.Contains(report.FlowMarkdown, "Source revision: `") || !strings.Contains(report.FlowMarkdown, "Source revision: working tree") {
		t.Fatalf("working-tree flow claimed a committed revision:\n%s", report.FlowMarkdown)
	}
	if report.FlowEvidence == "" || !strings.Contains(report.FlowEvidence, "Source evidence") {
		t.Fatalf("review omitted compact flow evidence: %q", report.FlowEvidence)
	}
	if provider.published == nil || !strings.Contains(provider.published.Summary, "## Application flows") {
		t.Fatalf("published review omitted flow: %+v", provider.published)
	}
}

func TestProviderFlowSourceReadsTheRequestedRevision(t *testing.T) {
	provider := &sourceRefProvider{stubProvider: stubProvider{content: map[string]string{"gone.go": "package p\nfunc Gone() {}\n"}}}
	source := providerFlowSource{provider: provider, ref: vcs.Ref{Base: "base", Head: "head"}}
	if _, err := source.ReadFile(context.Background(), prflow.Revision{SHA: "base"}, "gone.go"); err != nil {
		t.Fatal(err)
	}
	if provider.readRef.Head != "base" {
		t.Fatalf("base-side source read revision = %q, want base", provider.readRef.Head)
	}
}

func TestReviewFlowHonorsGeneratedFilePolicy(t *testing.T) {
	for _, skip := range []bool{true, false} {
		t.Run(map[bool]string{true: "skip", false: "include"}[skip], func(t *testing.T) {
			provider := &stubProvider{content: map[string]string{"api.go": "// Code generated by probe. DO NOT EDIT.\npackage p\nfunc Run() { helper() }\nfunc helper() {}\n"}}
			cfg := config.Defaults()
			cfg.Flow.Mode = config.FlowOn
			cfg.Flow.IncludeUnchanged = false
			cfg.Review.SkipGenerated = skip
			engine := &Engine{Provider: provider}
			result, markdown, evidence := engine.flow(context.Background(), vcs.Ref{}, &vcs.PullRequest{}, diff.Files{&diff.File{Path: "api.go", Kind: diff.ChangeAdded}}, cfg)
			if evidence == "" {
				t.Fatal("compact flow evidence is empty")
			}
			if skip {
				if len(result.Nodes) != 0 || !strings.Contains(markdown, "generated_file") {
					t.Fatalf("generated source was retained or silently skipped: %+v\n%s", result, markdown)
				}
			} else if len(result.Edges) == 0 {
				t.Fatalf("explicitly included generated source has no flow: %+v", result)
			}
		})
	}
}

func TestProviderFlowSourceReadsForkAndBaseRepositories(t *testing.T) {
	provider := &sourceRefProvider{stubProvider: stubProvider{content: map[string]string{"a.go": "package p\n"}}}
	source := providerFlowSource{provider: provider, ref: vcs.Ref{Owner: "base", Repo: "project", Number: 7}}
	for _, revision := range []prflow.Revision{{Repository: "fork/project", SHA: "head"}, {Repository: "base/project", SHA: "base"}} {
		if _, err := source.ReadFile(context.Background(), revision, "a.go"); err != nil {
			t.Fatal(err)
		}
		if provider.readRef.Owner+"/"+provider.readRef.Repo != revision.Repository || provider.readRef.Head != revision.SHA {
			t.Fatalf("revision=%+v read=%+v; source repository or revision changed", revision, provider.readRef)
		}
	}
}

func TestRenderFlowMarkdownUsesSeparateBaseEvidence(t *testing.T) {
	result := prflow.Result{
		Status: prflow.StatusPartial,
		Nodes:  []prflow.Node{{ID: "gone", Label: "gone", State: prflow.ChangeRemoved, Source: prflow.Location{Path: "gone.go", Line: 1}}},
	}
	markdown := renderFlowMarkdown(result, "https://github.com/fork/project/blob/head", "https://github.com/base/project/blob/base")
	if !strings.Contains(markdown, "/base/project/blob/base/gone.go#L1") || strings.Contains(markdown, "/fork/project/blob/head/gone.go#L1") {
		t.Fatalf("removed evidence uses wrong revision:\n%s", markdown)
	}
}

type sourceRefProvider struct {
	stubProvider
	readRef vcs.Ref
}

func (p *sourceRefProvider) FileContent(ctx context.Context, ref vcs.Ref, path string) ([]byte, error) {
	p.readRef = ref
	return p.stubProvider.FileContent(ctx, ref, path)
}

type incompleteSourceLinkProvider struct {
	stubProvider
}

func (p *incompleteSourceLinkProvider) SourceBase(_ context.Context, _ vcs.Ref, revision string) (string, error) {
	if revision == "head" {
		return "https://github.com/fork/project/blob/head", nil
	}
	return "", vcs.ErrNoSourceLink
}

func TestReviewFlowMarksMissingBaseSourceLinksForRemovedDeclarations(t *testing.T) {
	provider := &incompleteSourceLinkProvider{stubProvider: stubProvider{content: map[string]string{
		"gone.go": "package app\nfunc Gone() {}\n",
	}}}
	cfg := config.Defaults()
	cfg.Flow.Mode = config.FlowOn
	cfg.Flow.IncludeUnchanged = false
	engine := &Engine{Provider: provider}

	result, markdown, evidence := engine.flow(context.Background(), vcs.Ref{Number: 1, Head: "head"}, &vcs.PullRequest{
		HeadSHA: "head", BaseSHA: "base", HeadRepo: "fork/project", BaseRepo: "base/project",
	}, diff.Files{&diff.File{Path: "gone.go", OldPath: "gone.go", Kind: diff.ChangeDeleted}}, cfg)

	if result.Status != prflow.StatusPartial {
		t.Fatalf("status = %q, want partial", result.Status)
	}
	if !hasFlowOmission(result, "base_source_links_unavailable") {
		t.Fatalf("base source-link omission missing: %+v", result.Coverage.Omissions)
	}
	for _, rendered := range []string{markdown, evidence} {
		if !strings.Contains(rendered, "base_source_links_unavailable") {
			t.Errorf("rendered flow hid missing base links:\n%s", rendered)
		}
	}
}

func hasFlowOmission(result *prflow.Result, reason string) bool {
	for _, omission := range result.Coverage.Omissions {
		if omission.Reason == reason {
			return true
		}
	}
	return false
}
