package knowledge

import (
	"fmt"
	"os"
	"path"
	"sort"
	"strings"
)

// Which index a run retrieves from.
//
// One committed index was enough while one embedding model was supported, and
// it made the model a property of the binary: an operator who wanted a
// different embedder had to rebuild the application, because the vectors it
// would have queried were compiled in. Several indexes ship, keyed by the model
// that built them, and an operator can point at a file instead.
//
// They are separate files rather than one file holding several vector sets
// because they are separate artefacts: each is regenerated by its own provider,
// diffs on its own, and a run reads exactly one.

// SelectIndex returns the shipped index built by model.
//
// The error names what is available. A model with no shipped index is the
// ordinary way this fails, and "no index for openai/text-embedding-3-large"
// with the list beside it is an answer; a mismatch error thrown later by
// CheckModel is a puzzle.
func SelectIndex(model string) ([]byte, error) {
	want := strings.TrimSpace(strings.ToLower(model))
	shipped, err := shippedIndexes()
	if err != nil {
		return nil, err
	}
	if raw, ok := shipped[want]; ok {
		return raw, nil
	}

	have := make([]string, 0, len(shipped))
	for m := range shipped {
		have = append(have, m)
	}
	sort.Strings(have)
	return nil, fmt.Errorf("knowledge: no index ships for embedding model %q; "+
		"this build carries %s. Name one of those under models.embed, or build your own "+
		"with `nitpick knowledge-index` and name it under review.knowledge_index in a "+
		"file the repository under review does not supply",
		model, strings.Join(have, ", "))
}

// LoadIndexFile reads an operator's own index.
//
// The escape hatch that makes the embedding model configuration rather than a
// build: an operator whose provider is not one of the shipped ones runs
// `nitpick knowledge-index` and names the result. It is still checked against
// the corpus and the model like any other, so supplying one buys no exemption.
func LoadIndexFile(p string) ([]byte, error) {
	raw, err := os.ReadFile(p)
	if err != nil {
		return nil, fmt.Errorf("knowledge: read the index at %s: %w", p, err)
	}
	return raw, nil
}

// ShippedModels names every embedding model this build has an index for.
func ShippedModels() ([]string, error) {
	shipped, err := shippedIndexes()
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(shipped))
	for m := range shipped {
		out = append(out, m)
	}
	sort.Strings(out)
	return out, nil
}

// shippedIndexes reads every embedded index, keyed by its model, lower-cased.
//
// Keyed by what the file says rather than by its name: the filename is a
// convenience for a reader and the model inside it is the thing a query has to
// match, so a file renamed or misnamed cannot make a run query the wrong
// vectors.
func shippedIndexes() (map[string][]byte, error) {
	names, err := indexFS.ReadDir(indexDir)
	if err != nil {
		return nil, fmt.Errorf("knowledge: read the shipped indexes: %w", err)
	}
	out := map[string][]byte{}
	for _, f := range names {
		if f.IsDir() || !strings.HasSuffix(f.Name(), ".json") {
			continue
		}
		raw, err := indexFS.ReadFile(path.Join(indexDir, f.Name()))
		if err != nil {
			return nil, fmt.Errorf("knowledge: read %s: %w", f.Name(), err)
		}
		model, err := indexModel(raw)
		if err != nil {
			return nil, fmt.Errorf("knowledge: %s: %w", f.Name(), err)
		}
		if prior, ok := out[model]; ok && string(prior) != string(raw) {
			return nil, fmt.Errorf("knowledge: two shipped indexes claim model %q", model)
		}
		out[model] = raw
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("knowledge: this build ships no index")
	}
	return out, nil
}
