package main

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jdziat/open-nitpick/internal/config"
	"github.com/jdziat/open-nitpick/internal/prflow"
)

func TestRunFlowRefusesDisabledMode(t *testing.T) {
	err := runFlow(context.Background(), []string{"-repo", t.TempDir()})
	if err == nil || !strings.Contains(err.Error(), "flow mode is off") {
		t.Fatalf("runFlow error = %v, want disabled-mode error", err)
	}
}

func TestRunFlowDoesNotRequireAModelConfiguration(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, config.FileName), []byte("flow:\n  mode: auto\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv(config.EnvProvider, "")
	t.Setenv(config.EnvModel, "")
	if err := runFlow(context.Background(), []string{"-repo", root}); err == nil || strings.Contains(err.Error(), "model") {
		t.Fatalf("runFlow error = %v, should reach repository handling without model configuration", err)
	}
}

func TestRunFlowRejectsExplicitInvalidLimitsBeforeReadingSource(t *testing.T) {
	for _, args := range [][]string{{"-max-files", "-1"}, {"-max-bytes", "0"}, {"-max-depth-callers", "-1"}, {"-max-nodes", "-1"}, {"-timeout", "0s"}, {"-exclude", "["}} {
		root := t.TempDir()
		err := runFlow(context.Background(), append([]string{"-repo", root, "-mode", "on"}, args...))
		if err == nil || !strings.Contains(err.Error(), "flow.") {
			t.Fatalf("args=%v error=%v; invalid option must fail before attempting git", args, err)
		}
	}
}

func TestFlowConfigIgnoresUnavailableReviewModel(t *testing.T) {
	root := t.TempDir()
	name := filepath.Join(root, config.FileName)
	if err := os.WriteFile(name, []byte("models:\n  default:\n    provider: openai\nflow:\n  mode: on\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	cfg, err := loadFlowConfig(root, name)
	if err != nil || cfg.Flow.Mode != config.FlowOn {
		t.Fatalf("config=%+v error=%v; flow must not need a review model", cfg, err)
	}
}

func TestFlowExplicitMissingConfigFailsEarly(t *testing.T) {
	_, err := loadFlowConfig(t.TempDir(), filepath.Join(t.TempDir(), "missing.yaml"))
	if err == nil {
		t.Fatal("explicit missing configuration was ignored")
	}
}

func TestFlowMarkdownNamesEmptyResultStatus(t *testing.T) {
	got := flowMarkdown(prflow.Result{Version: 1, Status: prflow.StatusNoFlow, Explanation: "no changed declaration"})
	for _, want := range []string{"Status: **no_flow**", "No path was resolved", "not evidence"} {
		if !strings.Contains(got, want) {
			t.Errorf("markdown missing %q:\n%s", want, got)
		}
	}
}

func TestAnalyzeFlowReadsChangedGoFile(t *testing.T) {
	t.Setenv(config.EnvProvider, "synthetic")
	t.Setenv(config.EnvModel, "flow-test")
	root := t.TempDir()
	gitRun(t, root, "init", "-q")
	gitRun(t, root, "config", "user.email", "test@example.com")
	gitRun(t, root, "config", "user.name", "Test")
	path := filepath.Join(root, "main.go")
	if err := os.WriteFile(path, []byte("package main\n\nfunc main() { run() }\nfunc run() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	gitRun(t, root, "add", "main.go")
	gitRun(t, root, "commit", "-qm", "initial")
	entryConfig := config.Defaults()
	entryConfig.Flow.Entrypoints = []string{"main.run"}
	entryResult, _, err := analyzeFlow(context.Background(), root, "", "", entryConfig, config.FlowOn, "")
	if err != nil || len(entryResult.Edges) == 0 {
		t.Fatalf("explicit unchanged entrypoint was not analyzed: %+v, error: %v", entryResult, err)
	}
	if err := os.WriteFile(path, []byte("package main\n\nfunc main() { run() }\nfunc run() { helper() }\nfunc helper() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg := config.Defaults()
	result, markdown, err := analyzeFlow(context.Background(), root, "", "", cfg, config.FlowOn, "")
	if err != nil {
		t.Fatalf("analyzeFlow: %v", err)
	}
	if result.Status == prflow.StatusSkipped || len(result.Nodes) == 0 {
		t.Fatalf("result = %+v, want changed Go nodes", result)
	}
	if !strings.Contains(markdown, "```mermaid") || !strings.Contains(markdown, "main#46;run") {
		t.Fatalf("standalone flow did not use the canonical diagram renderer:\n%s", markdown)
	}
	cfg.Flow.Entrypoints = []string{"main.Absent"}
	if _, _, err := analyzeFlow(context.Background(), root, "", "", cfg, config.FlowOn, ""); err == nil || !strings.Contains(err.Error(), "entrypoint") {
		t.Fatalf("invalid explicit entrypoint did not fail: %v", err)
	}
	cfg.Flow.Entrypoints = nil
	cfg.Review.Ignore = []string{"main.go"}
	result, _, err = analyzeFlow(context.Background(), root, "", "", cfg, config.FlowAuto, "")
	if err != nil || result.Status != prflow.StatusSkipped || len(result.Nodes) != 0 {
		t.Fatalf("ignored CLI source was analyzed: result=%+v err=%v", result, err)
	}
	cfg.Review.Ignore = nil
	if err := os.WriteFile(path, []byte("// Code generated by probe. DO NOT EDIT.\npackage main\nfunc main() { run() }\nfunc run() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	result, markdown, err = analyzeFlow(context.Background(), root, "", "", cfg, config.FlowOn, "")
	if err != nil || len(result.Nodes) != 0 || !strings.Contains(markdown, "generated_file") {
		t.Fatalf("generated CLI source was retained or silently excluded: result=%+v err=%v", result, err)
	}
}

func gitRun(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, out)
	}
}
