package bundle

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/jdziat/open-nitpick/internal/config"
	"github.com/jdziat/open-nitpick/internal/diff"
	"github.com/jdziat/open-nitpick/internal/vcs"
)

// diffFor builds a one-file diff adding n lines to path, for shaping tests.
func diffFor(t *testing.T, path string, n int) diff.Files {
	t.Helper()

	var b strings.Builder
	fmt.Fprintf(&b, "diff --git a/%s b/%s\n--- a/%s\n+++ b/%s\n@@ -1,0 +1,%d @@\n", path, path, path, path, n)
	for i := 1; i <= n; i++ {
		fmt.Fprintf(&b, "+line %d\n", i)
	}

	files, err := diff.Parse([]byte(b.String()))
	if err != nil {
		t.Fatalf("parse generated diff: %v", err)
	}
	return files
}

func baseConfig() *config.Config {
	cfg := config.Defaults()
	cfg.Models.Default = config.ModelSpec{Provider: "openai", Model: "gpt-4o"}
	return cfg
}

func TestAssembleSkipsIgnoredFiles(t *testing.T) {
	cfg := baseConfig()
	files := diffFor(t, "vendor/x/y.go", 2)

	plan, err := Assemble(context.Background(), cfg, files, nil)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if plan.Files() != 0 {
		t.Errorf("files = %d, want 0", plan.Files())
	}
	if len(plan.Skipped) != 1 || plan.Skipped[0].Reason != ReasonIgnored {
		t.Errorf("skipped = %+v, want one ignored entry", plan.Skipped)
	}
}

func TestAssembleSkipsDeletedAndBinary(t *testing.T) {
	const d = `diff --git a/gone.go b/gone.go
deleted file mode 100644
--- a/gone.go
+++ /dev/null
@@ -1,1 +0,0 @@
-package main
diff --git a/img.bin b/img.bin
index 1..2 100644
Binary files a/img.bin and b/img.bin differ
`
	files, err := diff.Parse([]byte(d))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	plan, err := Assemble(context.Background(), baseConfig(), files, nil)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if plan.Files() != 0 {
		t.Errorf("files = %d, want 0", plan.Files())
	}

	reasons := map[string]string{}
	for _, s := range plan.Skipped {
		reasons[s.Path] = s.Reason
	}
	if reasons["gone.go"] != ReasonDeleted {
		t.Errorf("gone.go reason = %q, want %q", reasons["gone.go"], ReasonDeleted)
	}
	if reasons["img.bin"] != ReasonBinary {
		t.Errorf("img.bin reason = %q, want %q", reasons["img.bin"], ReasonBinary)
	}
}

func TestAssembleRecordsEverySkip(t *testing.T) {
	// A review that silently dropped files is indistinguishable from one that
	// found nothing, so every exclusion must be reported.
	cfg := baseConfig()
	cfg.Review.MaxFiles = 1

	files := append(diffFor(t, "a.go", 1), diffFor(t, "b.go", 1)...)

	plan, err := Assemble(context.Background(), cfg, files, nil)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if plan.Files() != 1 {
		t.Errorf("files = %d, want 1", plan.Files())
	}
	if len(plan.Skipped) != 1 || plan.Skipped[0].Reason != ReasonFileLimit {
		t.Errorf("skipped = %+v, want one max_files entry", plan.Skipped)
	}
}

func TestAssembleAttachesContent(t *testing.T) {
	files := diffFor(t, "a.go", 2)
	fetch := func(context.Context, string) ([]byte, error) {
		return []byte("package a\n\nfunc F() {}\n"), nil
	}

	plan, err := Assemble(context.Background(), baseConfig(), files, fetch)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	entry := plan.Batches[0].Entries[0]
	if !entry.HasContent() {
		t.Fatal("full file content should be attached")
	}

	rendered := Render(entry)
	if !strings.Contains(rendered, "Full file after the change") {
		t.Error("rendered entry should include the full file section")
	}
	// Numbered so the model can cite lines outside the diff.
	if !strings.Contains(rendered, "     1  package a") {
		t.Errorf("full file should be line-numbered:\n%s", rendered)
	}
}

func TestAssembleDegradesWhenContentUnavailable(t *testing.T) {
	// A fetch failure must not lose the file; the diff is still reviewable.
	files := diffFor(t, "a.go", 2)
	fetch := func(context.Context, string) ([]byte, error) {
		return nil, vcs.ErrNotFound
	}

	plan, err := Assemble(context.Background(), baseConfig(), files, fetch)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if plan.Files() != 1 {
		t.Fatalf("files = %d, want the file to still be reviewed", plan.Files())
	}
	if plan.Batches[0].Entries[0].HasContent() {
		t.Error("content should be empty when the fetch failed")
	}
	if len(plan.Degraded) != 1 || plan.Degraded[0].Reason != ReasonUnavailable {
		t.Errorf("degraded = %+v, want the unavailable reason recorded", plan.Degraded)
	}
	// The file WAS reviewed, so it must not also appear as skipped: the
	// renderer lists Skipped under "Files not reviewed".
	if len(plan.Skipped) != 0 {
		t.Errorf("skipped = %+v, want empty for a file that was reviewed", plan.Skipped)
	}
}

func TestAssembleSkipsGeneratedFiles(t *testing.T) {
	files := diffFor(t, "api.go", 2)
	fetch := func(context.Context, string) ([]byte, error) {
		return []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n"), nil
	}

	plan, err := Assemble(context.Background(), baseConfig(), files, fetch)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if plan.Files() != 0 {
		t.Errorf("generated file should be dropped entirely, got %d files", plan.Files())
	}
	if len(plan.Skipped) != 1 || plan.Skipped[0].Reason != ReasonGenerated {
		t.Errorf("skipped = %+v, want the generated reason", plan.Skipped)
	}
}

func TestSkipGeneratedIsConfigurable(t *testing.T) {
	cfg := baseConfig()
	cfg.Review.SkipGenerated = false

	files := diffFor(t, "api.go", 2)
	fetch := func(context.Context, string) ([]byte, error) {
		return []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n"), nil
	}

	plan, err := Assemble(context.Background(), cfg, files, fetch)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if plan.Files() != 1 {
		t.Error("generated files should be reviewed when skip_generated is off")
	}
}

func TestIsGeneratedOnlyScansTheTop(t *testing.T) {
	// An ordinary comment deep in a file must not suppress its review.
	body := strings.Repeat("// ordinary code\n", 40) + "// DO NOT EDIT this by hand\n"
	if isGenerated(body) {
		t.Error("a marker far into the file should not count as generated")
	}
	if !isGenerated("// Code generated by tool. DO NOT EDIT.\npackage x\n") {
		t.Error("a leading marker should count as generated")
	}
}

func TestAssembleSkipsNonUTF8(t *testing.T) {
	files := diffFor(t, "a.go", 2)
	fetch := func(context.Context, string) ([]byte, error) {
		return []byte{0xff, 0xfe, 0x00}, nil
	}

	plan, err := Assemble(context.Background(), baseConfig(), files, fetch)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if plan.Batches[0].Entries[0].HasContent() {
		t.Error("invalid UTF-8 should not be attached as content")
	}
	if len(plan.Degraded) != 1 || plan.Degraded[0].Reason != ReasonNotText {
		t.Errorf("degraded = %+v, want the non-text reason", plan.Degraded)
	}
	if len(plan.Skipped) != 0 {
		t.Errorf("skipped = %+v, want empty for a file that was reviewed", plan.Skipped)
	}
}

func TestAssembleRespectsMaxFileBytes(t *testing.T) {
	cfg := baseConfig()
	cfg.Review.MaxFileBytes = 10

	files := diffFor(t, "a.go", 2)
	fetch := func(context.Context, string) ([]byte, error) {
		return []byte(strings.Repeat("x", 100)), nil
	}

	plan, err := Assemble(context.Background(), cfg, files, fetch)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if plan.Batches[0].Entries[0].HasContent() {
		t.Error("oversized file content should not be attached")
	}
	if len(plan.Degraded) != 1 || plan.Degraded[0].Reason != ReasonTooLarge {
		t.Errorf("degraded = %+v, want %q", plan.Degraded, ReasonTooLarge)
	}
	if len(plan.Skipped) != 0 {
		t.Errorf("skipped = %+v, want empty for a file that was reviewed", plan.Skipped)
	}
}

func TestBatchingRespectsFileCount(t *testing.T) {
	cfg := baseConfig()
	cfg.Review.MaxFilesPerRequest = 2

	var files diff.Files
	for i := range 5 {
		files = append(files, diffFor(t, fmt.Sprintf("f%d.go", i), 1)...)
	}

	plan, err := Assemble(context.Background(), cfg, files, nil)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if len(plan.Batches) != 3 {
		t.Fatalf("batches = %d, want 3 for 5 files at 2 per request", len(plan.Batches))
	}
	for i, b := range plan.Batches {
		if len(b.Entries) > 2 {
			t.Errorf("batch %d has %d entries, want at most 2", i, len(b.Entries))
		}
	}
	if plan.Files() != 5 {
		t.Errorf("total files = %d, want 5: batching must not lose files", plan.Files())
	}
}

func TestBatchingRespectsTokenBudget(t *testing.T) {
	cfg := baseConfig()
	cfg.Review.MaxFilesPerRequest = 100
	cfg.Review.TokenBudgetPerRequest = 400

	var files diff.Files
	for i := range 6 {
		files = append(files, diffFor(t, fmt.Sprintf("f%d.go", i), 30)...)
	}

	plan, err := Assemble(context.Background(), cfg, files, nil)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if len(plan.Batches) < 2 {
		t.Fatalf("batches = %d, want the budget to force a split", len(plan.Batches))
	}
	for i, b := range plan.Batches {
		if len(b.Entries) > 1 && b.Tokens > cfg.Review.TokenBudgetPerRequest {
			t.Errorf("batch %d has %d tokens, over the %d budget", i, b.Tokens, cfg.Review.TokenBudgetPerRequest)
		}
	}
}

func TestOversizedSingleFileStillGetsReviewed(t *testing.T) {
	// Dropping it would silently skip a real file; an over-budget request is
	// at least a visible failure.
	cfg := baseConfig()
	cfg.Review.TokenBudgetPerRequest = 50

	files := diffFor(t, "big.go", 500)

	plan, err := Assemble(context.Background(), cfg, files, nil)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	if plan.Files() != 1 {
		t.Errorf("files = %d, want the oversized file to still be batched", plan.Files())
	}
}

func TestLargeFileContentIsWindowed(t *testing.T) {
	cfg := baseConfig()
	cfg.Review.TokenBudgetPerRequest = 900

	// A small change in a large file: the window should keep the changed
	// region and elide the rest rather than dropping context entirely.
	const changedLine = 3
	files := diffFor(t, "big.go", changedLine)

	var body strings.Builder
	for i := 1; i <= 2000; i++ {
		fmt.Fprintf(&body, "line %d of a very long file\n", i)
	}
	fetch := func(context.Context, string) ([]byte, error) { return []byte(body.String()), nil }

	plan, err := Assemble(context.Background(), cfg, files, fetch)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	entry := plan.Batches[0].Entries[0]
	if !entry.Truncated {
		t.Fatalf("content should have been windowed; tokens=%d budget=%d hasContent=%v",
			entry.Tokens, cfg.Review.TokenBudgetPerRequest, entry.HasContent())
	}
	if !strings.Contains(entry.Content, "unchanged lines omitted") {
		t.Error("windowed content should mark what it elided")
	}
	// The region around the change survives.
	if !strings.Contains(entry.Content, "line 1 of a very long file") {
		t.Error("window should keep lines around the change")
	}
	if strings.Contains(entry.Content, "line 1500 of a very long file") {
		t.Error("window should elide distant lines")
	}

	rendered := Render(entry)
	if strings.Count(rendered, "unchanged lines omitted") == 0 {
		t.Error("rendered entry should show the elision markers")
	}
	// Windowed content is pre-numbered; numbering it again would produce
	// line numbers that do not match the file.
	if strings.Contains(rendered, "     1       1  line 1") {
		t.Error("windowed content was numbered twice")
	}
}

func TestInstructionsAttachToMatchingFiles(t *testing.T) {
	cfg := baseConfig()
	cfg.Instructions = []config.Instruction{
		{Path: "**/*.go", Prompt: "check error handling"},
		{Path: "**/*.py", Prompt: "irrelevant here"},
	}

	files := diffFor(t, "a.go", 1)

	plan, err := Assemble(context.Background(), cfg, files, nil)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	entry := plan.Batches[0].Entries[0]
	if len(entry.Instructions) != 1 || entry.Instructions[0] != "check error handling" {
		t.Fatalf("instructions = %v, want only the Go one", entry.Instructions)
	}
	if !strings.Contains(Render(entry), "check error handling") {
		t.Error("instructions should reach the prompt")
	}
	if strings.Contains(Render(entry), "irrelevant here") {
		t.Error("non-matching instructions must not leak into the prompt")
	}
}

func TestRenderIncludesDiffAndLineNumbers(t *testing.T) {
	files := diffFor(t, "a.go", 2)
	plan, _ := Assemble(context.Background(), baseConfig(), files, nil)

	out := Render(plan.Batches[0].Entries[0])
	if !strings.Contains(out, "### File: a.go") {
		t.Error("rendered entry should name the file")
	}
	if !strings.Contains(out, "```diff") {
		t.Error("rendered entry should contain the diff")
	}
	if !strings.Contains(out, "1 + line 1") {
		t.Errorf("diff lines should carry new-file line numbers:\n%s", out)
	}
}

func TestAssembleNilConfig(t *testing.T) {
	if _, err := Assemble(context.Background(), nil, nil, nil); err == nil {
		t.Fatal("want error for a nil config")
	}
}

func TestAssembleHonorsContextCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	files := diffFor(t, "a.go", 1)
	if _, err := Assemble(ctx, baseConfig(), files, nil); err == nil {
		t.Fatal("want error for a cancelled context")
	}
}

func TestWindowSurvivesChangedLinesPastEndOfFile(t *testing.T) {
	// Raised as an "error" by open-nitpick reviewing its own history: that a
	// changed line number beyond the file's length would write past the end of
	// the keep slice. It cannot -- hi is clamped to len(lines), so the fill
	// loop does not run when lo exceeds it -- but the mismatch it assumes is
	// real. ChangedLines yields new-file numbers while content may be fetched
	// at a different revision, so this pins the property rather than trusting
	// the clamp to survive a future edit.
	f := &diff.File{Path: "a.go", Hunks: []diff.Hunk{{
		NewStart: 9000,
		Lines:    []diff.Line{{Kind: diff.LineAdded, NewLine: 9000, Content: "x"}},
	}}}

	got, elided := window("one\ntwo\nthree\n", f)

	// Nothing is in range, so nothing is kept and everything reads as elided.
	if strings.Contains(got, "9000") {
		t.Errorf("a line past EOF should not be emitted:\n%s", got)
	}
	_ = elided
}
