package bundle

import (
	"fmt"
	"strings"

	"github.com/jdziat/open-nitpick/internal/diff"
)

// generatedMarkers are substrings that mark machine-generated files. The Go
// convention is the first; the others cover common generators in other
// ecosystems.
var generatedMarkers = []string{
	"Code generated by",
	"@generated",
	"DO NOT EDIT",
	"autogenerated by",
	"This file was automatically generated",
	"AUTOGENERATED FILE",
}

// generatedScanLines bounds how far into a file the marker is looked for.
// Conventions put it at the top; scanning the whole file would let an ordinary
// comment mentioning "DO NOT EDIT" suppress a real review.
const generatedScanLines = 8

// isGenerated reports whether content looks machine-generated.
func isGenerated(content string) bool {
	for i, line := range strings.SplitN(content, "\n", generatedScanLines+1) {
		if i >= generatedScanLines {
			break
		}
		for _, marker := range generatedMarkers {
			if strings.Contains(line, marker) {
				return true
			}
		}
	}
	return false
}

// windowContext is how many lines of surrounding code a window keeps on each
// side of a changed region. Enough to see the enclosing function's shape
// without pulling in the whole file.
const windowContext = 40

// window reduces a file to the regions around its changed lines, joined by
// elision markers. It is the fallback when a whole file will not fit the token
// budget: a window is far better than the diff alone, because the model still
// sees declarations and neighboring code.
//
// It returns text that is already line-numbered, since the elision markers
// occupy no line number of their own. The bool reports whether anything was
// actually elided.
func window(content string, f *diff.File) (string, bool) {
	lines := splitLines(content)
	if len(lines) == 0 {
		return content, false
	}

	changed := f.ChangedLines()
	if len(changed) == 0 {
		return content, false
	}

	keep := make([]bool, len(lines)+1) // 1-based
	for _, ln := range changed {
		lo := max(1, ln-windowContext)
		hi := min(len(lines), ln+windowContext)
		for i := lo; i <= hi; i++ {
			keep[i] = true
		}
	}

	var (
		b       strings.Builder
		elided  bool
		inGap   bool
		emitted int
	)

	for i := 1; i <= len(lines); i++ {
		if keep[i] {
			if inGap {
				fmt.Fprintf(&b, "%6s  … unchanged lines omitted …\n", "")
				inGap = false
			}
			fmt.Fprintf(&b, "%6d  %s\n", i, lines[i-1])
			emitted++
			continue
		}

		if !inGap {
			inGap = true
			elided = true
		}
	}

	if inGap {
		fmt.Fprintf(&b, "%6s  … unchanged lines omitted …\n", "")
	}

	if emitted == 0 {
		return content, false
	}
	return b.String(), elided
}

// splitLines splits content into lines without a trailing empty element.
func splitLines(content string) []string {
	if content == "" {
		return nil
	}

	lines := strings.Split(content, "\n")
	if lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	return lines
}
