package bundle

import (
	"context"
	"errors"
	"slices"
	"strings"
	"testing"

	"github.com/jdziat/open-nitpick/internal/config"
)

func TestDesignSourceCaptureKeepsBudgetOmissionsOutOfContext(t *testing.T) {
	cfg := config.Defaults()
	reads := map[string]int{}
	source := []byte("package visible\n")
	fetch := func(_ context.Context, name string) ([]byte, error) { reads[name]++; return source, nil }
	list := func(_ context.Context, dir string) ([]string, error) {
		if dir != "" {
			return nil, errors.New("unexpected directory")
		}
		return []string{"visible.go", "hidden.go", "go.mod"}, nil
	}
	view := CaptureDesignSources(t.Context(), cfg, []string{"visible.go"}, fetch, list, []Skip{{Path: "hidden.go", Reason: "tree budget"}}, SourceLimits{Paths: 20, Bytes: 1000})
	if reads["hidden.go"] != 0 || reads["visible.go"] != 1 || len(view.Omitted) != 1 || view.Omitted[0].Path != "hidden.go" {
		t.Fatalf("capture=%+v reads=%v", view, reads)
	}
	source[0] = 'X'
	if string(view.Content["visible.go"]) != "package visible\n" {
		t.Fatal("captured bytes still alias provider source")
	}
}

func TestDesignSourceCaptureReportsIncompleteCallerInventory(t *testing.T) {
	cfg := config.Defaults()
	fetch := func(_ context.Context, _ string) ([]byte, error) { return []byte("package source\n"), nil }
	list := func(_ context.Context, _ string) ([]string, error) { return []string{"a.go", "b.go", "c.go"}, nil }
	bounded := CaptureDesignSources(t.Context(), cfg, []string{"a.go"}, fetch, list, nil, SourceLimits{Paths: 1, Bytes: 1000})
	if len(bounded.Errors) == 0 || len(bounded.Content) != 1 {
		t.Fatalf("bounded=%+v", bounded)
	}
	unavailable := CaptureDesignSources(t.Context(), cfg, []string{"a.go"}, fetch, nil, nil, SourceLimits{Paths: 10, Bytes: 1000})
	if len(unavailable.Errors) == 0 || len(unavailable.Content) != 1 {
		t.Fatalf("unavailable=%+v", unavailable)
	}
}

func TestDesignSourceCapturePreservesExclusionsAndUnreadableFiles(t *testing.T) {
	cfg := config.Defaults()
	cfg.Review.Ignore = append(cfg.Review.Ignore, "private.go")
	var reads []string
	fetch := func(_ context.Context, name string) ([]byte, error) {
		reads = append(reads, name)
		if name == "missing.go" {
			return nil, errors.New("unreadable")
		}
		return []byte("// Code generated by fixture; DO NOT EDIT.\npackage source\n"), nil
	}
	list := func(_ context.Context, _ string) ([]string, error) {
		return []string{"private.go", "generated.go", "missing.go"}, nil
	}
	view := CaptureDesignSources(t.Context(), cfg, nil, fetch, list, nil, SourceLimits{Paths: 10, Bytes: 1000})
	if slices.Contains(reads, "private.go") || len(view.Content) != 0 || len(view.Excluded) != 2 || len(view.Omitted) != 1 {
		t.Fatalf("capture=%+v reads=%v", view, reads)
	}
}

func TestDesignSourceCaptureBoundsExplicitChangesAndRejectsTraversal(t *testing.T) {
	cfg := config.Defaults()
	var reads []string
	fetch := func(_ context.Context, name string) ([]byte, error) {
		reads = append(reads, name)
		return []byte("package source\n"), nil
	}
	view := CaptureDesignSources(t.Context(), cfg, []string{"../outside.go", "a.go", "b.go", "c.go"}, fetch, nil, nil, SourceLimits{Paths: 1, Bytes: 1000})
	if !slices.Equal(reads, []string{"a.go"}) || len(view.Content) != 1 || len(view.Omitted) != 3 {
		t.Fatalf("scope escaped bounds: %+v reads=%v", view, reads)
	}
}

func TestDesignSourceCaptureExcludesRepositoryMetadataBeforeWalking(t *testing.T) {
	list := func(_ context.Context, dir string) ([]string, error) {
		if dir != "" {
			t.Fatalf("walk entered repository metadata: %s", dir)
		}
		return []string{".git/", "app.go", "go.mod"}, nil
	}
	fetch := func(_ context.Context, name string) ([]byte, error) {
		if strings.Contains(name, ".git/") {
			t.Fatalf("explicit metadata path was read: %s", name)
		}
		return []byte("source"), nil
	}
	view := CaptureDesignSources(t.Context(), config.Defaults(), []string{"app.go", ".git/hidden.go"}, fetch, list, nil, SourceLimits{Paths: 4, Bytes: 1024})
	if len(view.Errors) != 0 || len(view.Content) != 2 || len(view.Excluded) != 2 {
		t.Fatalf("metadata consumed source inventory or disappeared without an exclusion: %+v", view)
	}
}
