package bundle

import (
	"context"
	"errors"
	"fmt"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/jdziat/open-nitpick/internal/config"
)

func TestDesignSourceCaptureKeepsBudgetOmissionsOutOfContext(t *testing.T) {
	cfg := config.Defaults()
	reads := map[string]int{}
	source := []byte("package visible\n")
	var mu sync.Mutex
	fetch := func(_ context.Context, name string) ([]byte, error) {
		mu.Lock()
		defer mu.Unlock()
		reads[name]++
		return source, nil
	}
	list := func(_ context.Context, dir string) ([]string, error) {
		if dir != "" {
			return nil, errors.New("unexpected directory")
		}
		return []string{"visible.go", "hidden.go", "go.mod"}, nil
	}
	view := CaptureDesignSources(t.Context(), cfg, []string{"visible.go"}, fetch, list, []Skip{{Path: "hidden.go", Reason: "tree budget"}}, SourceLimits{Paths: 20, Bytes: 1000})
	if reads["hidden.go"] != 0 || reads["visible.go"] != 1 || len(view.Omitted) != 1 || view.Omitted[0].Path != "hidden.go" {
		t.Fatalf("capture=%+v reads=%v", view, reads)
	}
	source[0] = 'X'
	if string(view.Content["visible.go"]) != "package visible\n" {
		t.Fatal("captured bytes still alias provider source")
	}
}

func TestDesignSourceCaptureReportsIncompleteCallerInventory(t *testing.T) {
	cfg := config.Defaults()
	fetch := func(_ context.Context, _ string) ([]byte, error) { return []byte("package source\n"), nil }
	list := func(_ context.Context, _ string) ([]string, error) { return []string{"a.go", "b.go", "c.go"}, nil }
	bounded := CaptureDesignSources(t.Context(), cfg, []string{"a.go"}, fetch, list, nil, SourceLimits{Paths: 1, Bytes: 1000})
	if len(bounded.Errors) == 0 || len(bounded.Content) != 1 {
		t.Fatalf("bounded=%+v", bounded)
	}
	unavailable := CaptureDesignSources(t.Context(), cfg, []string{"a.go"}, fetch, nil, nil, SourceLimits{Paths: 10, Bytes: 1000})
	if len(unavailable.Errors) == 0 || len(unavailable.Content) != 1 {
		t.Fatalf("unavailable=%+v", unavailable)
	}
}

func TestDesignSourceCapturePreservesExclusionsAndUnreadableFiles(t *testing.T) {
	cfg := config.Defaults()
	cfg.Review.Ignore = append(cfg.Review.Ignore, "private.go")
	var reads []string
	var mu sync.Mutex
	fetch := func(_ context.Context, name string) ([]byte, error) {
		mu.Lock()
		defer mu.Unlock()
		reads = append(reads, name)
		if name == "missing.go" {
			return nil, errors.New("unreadable")
		}
		return []byte("// Code generated by fixture; DO NOT EDIT.\npackage source\n"), nil
	}
	list := func(_ context.Context, _ string) ([]string, error) {
		return []string{"private.go", "generated.go", "missing.go"}, nil
	}
	view := CaptureDesignSources(t.Context(), cfg, nil, fetch, list, nil, SourceLimits{Paths: 10, Bytes: 1000})
	if slices.Contains(reads, "private.go") || len(view.Content) != 0 || len(view.Excluded) != 2 || len(view.Omitted) != 1 {
		t.Fatalf("capture=%+v reads=%v", view, reads)
	}
}

func TestDesignSourceCaptureBoundsExplicitChangesAndRejectsTraversal(t *testing.T) {
	cfg := config.Defaults()
	var reads []string
	fetch := func(_ context.Context, name string) ([]byte, error) {
		reads = append(reads, name)
		return []byte("package source\n"), nil
	}
	view := CaptureDesignSources(t.Context(), cfg, []string{"../outside.go", "a.go", "b.go", "c.go"}, fetch, nil, nil, SourceLimits{Paths: 1, Bytes: 1000})
	if !slices.Equal(reads, []string{"a.go"}) || len(view.Content) != 1 || len(view.Omitted) != 3 {
		t.Fatalf("scope escaped bounds: %+v reads=%v", view, reads)
	}
}

func TestDesignSourceCaptureExcludesRepositoryMetadataBeforeWalking(t *testing.T) {
	list := func(_ context.Context, dir string) ([]string, error) {
		if dir != "" {
			t.Fatalf("walk entered repository metadata: %s", dir)
		}
		return []string{".git/", "app.go", "go.mod"}, nil
	}
	fetch := func(_ context.Context, name string) ([]byte, error) {
		if strings.Contains(name, ".git/") {
			t.Fatalf("explicit metadata path was read: %s", name)
		}
		return []byte("source"), nil
	}
	view := CaptureDesignSources(t.Context(), config.Defaults(), []string{"app.go", ".git/hidden.go"}, fetch, list, nil, SourceLimits{Paths: 4, Bytes: 1024})
	if len(view.Errors) != 0 || len(view.Content) != 2 || len(view.Excluded) != 2 {
		t.Fatalf("metadata consumed source inventory or disappeared without an exclusion: %+v", view)
	}
}

// slowRepo is a repository whose every request costs delay, the way a forge
// does. It records how many requests were in flight at once.
type slowRepo struct {
	delay   time.Duration
	dirs    map[string][]string
	files   map[string]string
	mu      sync.Mutex
	active  int
	peak    int
	fActive int
	fPeak   int
	lActive int
	lPeak   int
	gate    int
	gateFor int
	gateSet time.Duration
	latch   chan struct{}
	latchOn sync.Once
	listed  []string
	fetched []string
}

func (r *slowRepo) enter() func() {
	r.mu.Lock()
	r.active++
	r.peak = max(r.peak, r.active)
	r.mu.Unlock()
	time.Sleep(r.delay)
	return func() { r.mu.Lock(); r.active--; r.mu.Unlock() }
}

func (r *slowRepo) list(ctx context.Context, dir string) ([]string, error) {
	defer r.enter()()
	r.mu.Lock()
	r.listed = append(r.listed, dir)
	r.lActive++
	r.lPeak = max(r.lPeak, r.lActive)
	wait := r.latch != nil && r.gateFor > 0
	if wait {
		r.gateFor--
		if r.lActive >= r.gate {
			r.latchOn.Do(func() { close(r.latch) })
		}
	}
	r.mu.Unlock()
	if wait {
		select {
		case <-r.latch:
		case <-time.After(r.gateSet):
		case <-ctx.Done():
		}
	}
	defer func() { r.mu.Lock(); r.lActive--; r.mu.Unlock() }()
	entries, ok := r.dirs[dir]
	if !ok {
		return nil, errors.New("no such directory")
	}
	return slices.Clone(entries), nil
}

// counts reports how many listings and reads the repo served, under the lock
// the goroutines append with.
func (r *slowRepo) counts() (listed, fetched int) {
	r.mu.Lock()
	defer r.mu.Unlock()
	return len(r.listed), len(r.fetched)
}

func (r *slowRepo) fetch(ctx context.Context, name string) ([]byte, error) {
	defer r.enter()()
	r.mu.Lock()
	r.fetched = append(r.fetched, name)
	r.fActive++
	r.fPeak = max(r.fPeak, r.fActive)
	wait := r.latch != nil && r.gateFor > 0
	if wait {
		r.gateFor--
		if r.fActive >= r.gate {
			r.latchOn.Do(func() { close(r.latch) })
		}
	}
	r.mu.Unlock()
	if wait {
		select {
		case <-r.latch:
		case <-time.After(r.gateSet):
		case <-ctx.Done():
		}
	}
	defer func() { r.mu.Lock(); r.fActive--; r.mu.Unlock() }()
	body, ok := r.files[name]
	if !ok {
		return nil, errors.New("no such file")
	}
	return []byte(body), nil
}

// wideRepo has dirs directories of files Go files each.
func wideRepo(delay time.Duration, dirs, files int) *slowRepo {
	r := &slowRepo{delay: delay, dirs: map[string][]string{}, files: map[string]string{}}
	var top []string
	for d := range dirs {
		dir := fmt.Sprintf("pkg%02d", d)
		top = append(top, dir+"/")
		var entries []string
		for f := range files {
			name := fmt.Sprintf("f%02d.go", f)
			entries = append(entries, name)
			r.files[dir+"/"+name] = "package " + dir + "\n"
		}
		r.dirs[dir] = entries
	}
	r.dirs[""] = top
	return r
}

// A forge answers each listing and each read with a request. Reading a
// repository one request at a time spent a minute before the first model call
// in CI (issue #167); requests that do not depend on one another overlap.
func TestDesignSourceCaptureOverlapsRequestsAndStaysWithinTheLimit(t *testing.T) {
	repo := wideRepo(0, 20, 10)
	// Hold the first reads open until a second coexists. A serial reader hits
	// the deadline with only one active and fails the peak check below; a
	// concurrent one clears the gate immediately.
	repo.gate = 2
	repo.gateFor = 2
	repo.gateSet = time.Second
	repo.latch = make(chan struct{})

	view := CaptureDesignSources(t.Context(), config.Defaults(), nil, repo.fetch, repo.list, nil, SourceLimits{Paths: 4096, Bytes: 1 << 20})

	if len(view.Content) != 200 || len(view.Errors) != 0 {
		t.Fatalf("read %d of 200 files, errors %v", len(view.Content), view.Errors)
	}
	// Peak reads in flight, not wall clock, proves overlap: serial reads never
	// have two bodies outstanding, however fast the runner is. Listing overlap
	// is checked by repo.peak, which concurrent fetches must not be doing alone.
	if repo.fPeak < 2 {
		t.Errorf("peak reads in flight = %d, want overlap", repo.fPeak)
	}
	if repo.peak < 2 {
		t.Errorf("peak requests in flight = %d, want overlap", repo.peak)
	}
	if repo.peak > readConcurrency {
		t.Errorf("peak requests in flight = %d, over the limit of %d", repo.peak, readConcurrency)
	}
}

// A cancelled walk does not start work it queued. The callbacks hold every
// slot open, so the only way past them is for the loop to watch ctx; the old
// loop instead waited on a slot and started one more callback once a worker
// freed, which is what the count of readConcurrency pins here.
func TestInParallelStopsQueuedWorkWhenTheContextIsCancelled(t *testing.T) {
	ctx, cancel := context.WithCancel(t.Context())
	release := make(chan struct{})
	var mu sync.Mutex
	var count int
	blocked := make(chan struct{})

	done := make(chan struct{})
	go func() {
		defer close(done)
		inParallel(ctx, 1000, func(i int) {
			mu.Lock()
			count++
			running := count
			mu.Unlock()
			if running == readConcurrency {
				close(blocked)
			}
			<-release
		})
	}()

	<-blocked
	cancel()
	close(release)
	<-done

	mu.Lock()
	defer mu.Unlock()
	if count != readConcurrency {
		t.Errorf("started %d callbacks, want exactly %d: no work should start after cancellation", count, readConcurrency)
	}
}

// The walk refills listings as answers arrive instead of waiting for a whole
// window. Pinning that as peak listings in flight rather than wall clock keeps
// the test honest on a loaded runner: a barrier walk never has a listing
// outstanding across two windows, however fast it runs.
func TestDesignSourceCaptureListingsOverlapWithoutWindowBarriers(t *testing.T) {
	repo := wideRepo(0, 30, 3)
	repo.gate = 2
	repo.gateFor = 2
	// Short: the root is listed alone, so it waits this out, but 50ms is
	// plenty for the next eight listings of the root's children to overlap it.
	repo.gateSet = 50 * time.Millisecond
	repo.latch = make(chan struct{})

	view := CaptureDesignSources(t.Context(), config.Defaults(), nil, repo.fetch, repo.list, nil, SourceLimits{Paths: 4096, Bytes: 1 << 20})
	if len(view.Errors) != 0 || len(view.Content) != 90 {
		t.Fatalf("read %d files, errors %v", len(view.Content), view.Errors)
	}
	if repo.lPeak < 2 {
		t.Errorf("peak listings in flight = %d, want overlap", repo.lPeak)
	}
}

// The stream reads ahead but hands answers back in order, whatever order the
// bytes arrive in.
func TestFetchStreamDeliversInOrderDespiteSlowFirstRead(t *testing.T) {
	want := []string{"a", "b", "c", "d"}
	fetch := func(_ context.Context, name string) ([]byte, error) {
		if name == "a" {
			time.Sleep(30 * time.Millisecond)
		}
		return []byte(name), nil
	}
	s := newFetchStream(t.Context(), want, 4, fetch)
	defer s.stop()
	for _, name := range want {
		got, ok := s.next()
		if !ok || string(got.content) != name {
			t.Fatalf("next() = %q ok=%v, want %q", got.content, ok, name)
		}
	}
}

// Overlap changes when requests are made and not what is kept: the path limit
// cuts the same files off, and the same files are read, as in a serial walk.
func TestDesignSourceCaptureKeepsTheSameFilesAtThePathLimit(t *testing.T) {
	serial := wideRepo(0, 6, 5)
	limits := SourceLimits{Paths: 17, Bytes: 1 << 20}
	got := CaptureDesignSources(t.Context(), config.Defaults(), nil, serial.fetch, serial.list, nil, limits)

	var keep []string
	for name := range got.Content {
		keep = append(keep, name)
	}
	slices.Sort(keep)

	// The walk visits "" first, then pkg00, pkg01, ... in sorted order, so the
	// 17 paths are the 6 directories and the first 11 files of the first three.
	want := []string{
		"pkg00/f00.go", "pkg00/f01.go", "pkg00/f02.go", "pkg00/f03.go", "pkg00/f04.go",
		"pkg01/f00.go", "pkg01/f01.go", "pkg01/f02.go", "pkg01/f03.go", "pkg01/f04.go",
		"pkg02/f00.go",
	}
	if !slices.Equal(keep, want) {
		t.Fatalf("kept %v, want %v", keep, want)
	}
	if !slices.Contains(got.Errors, "design inventory path limit reached; callers may be missing") {
		t.Errorf("hitting the limit was not reported: %v", got.Errors)
	}
	slices.Sort(serial.fetched)
	if !slices.Equal(serial.fetched, want) {
		t.Errorf("fetched %v, want exactly the kept files %v", serial.fetched, want)
	}
	// Prefetching stays inside the same bound: files the ordered pass would cut
	// off are never requested, so overlap cannot turn the limit into a wider read.
	for _, name := range serial.fetched {
		if strings.HasPrefix(name, "pkg04/") || strings.HasPrefix(name, "pkg05/") {
			t.Errorf("fetched %s beyond the path limit", name)
		}
	}
}

// A wide level is where the path limit has to stop the walk and not just the
// reads. The root's 20 directories are under the limit, so the limit is spent
// inside the next level; listing that level one window at a time leaves at
// most readConcurrency-1 directories listed and then discarded, where listing
// the whole level first would request all 20.
func TestDesignSourceCaptureBoundsListingsPastThePathLimit(t *testing.T) {
	const dirs, files, paths = 20, 30, 50
	repo := wideRepo(0, dirs, files)
	view := CaptureDesignSources(t.Context(), config.Defaults(), nil, repo.fetch, repo.list, nil, SourceLimits{Paths: paths, Bytes: 1 << 20})

	if !slices.Contains(view.Errors, "design inventory path limit reached; callers may be missing") {
		t.Fatalf("path limit was not reported: %v", view.Errors)
	}
	listed, fetched := repo.counts()
	// The walk keeps readConcurrency listings in flight and starts one more
	// each time it consumes an answer, so a limit hit after the first
	// directory leaves at most two windows started. Listing the whole level
	// first would show all 20.
	if listed > 2*readConcurrency {
		t.Errorf("listed %d directories, want at most %d: the limit must stop the walk, not just the reads", listed, 2*readConcurrency)
	}
	if fetched > paths {
		t.Errorf("fetched %d files past the %d-path limit", fetched, paths)
	}
}

// The prefetch stream must never report a miss. It is built from every name
// designCandidate admits, so it stays a superset of what the loop reads no
// matter how the path and byte limits interleave. This sweeps those
// combinations: a byte budget that drops a name before any read, a path limit
// that stops the loop, and both together.
func TestDesignSourceCaptureNeverReportsAPrefetchMissUnderEitherLimit(t *testing.T) {
	for _, paths := range []int{0, 1, 3, 7} {
		for _, bytes := range []int{0, 5, 40, 4000} {
			repo := wideRepo(0, 4, 6)
			view := CaptureDesignSources(t.Context(), config.Defaults(), nil, repo.fetch, repo.list, nil, SourceLimits{Paths: paths, Bytes: bytes})
			for _, err := range view.Errors {
				if strings.Contains(err, "prefetch missed") {
					t.Fatalf("paths=%d bytes=%d: %s", paths, bytes, err)
				}
			}
		}
	}
}

// A failed request is reported against its own directory and file, and does
// not stop the others.
func TestDesignSourceCaptureReportsEachFailedRequestOnce(t *testing.T) {
	repo := wideRepo(0, 4, 3)
	delete(repo.dirs, "pkg01")
	delete(repo.files, "pkg02/f01.go")

	view := CaptureDesignSources(t.Context(), config.Defaults(), nil, repo.fetch, repo.list, nil, SourceLimits{Paths: 100, Bytes: 1 << 20})

	if len(view.Content) != 8 {
		t.Errorf("read %d files, want 8 (3 directories of 3, minus one file)", len(view.Content))
	}
	if !slices.Contains(view.Errors, "pkg01: directory listing unavailable") {
		t.Errorf("the failed listing was not reported: %v", view.Errors)
	}
	var gone []string
	for _, o := range view.Omitted {
		gone = append(gone, o.Path)
	}
	if !slices.Equal(gone, []string{"pkg02/f01.go"}) {
		t.Errorf("omitted %v, want only pkg02/f01.go", gone)
	}
}
