// Package sourcepolicy shares source eligibility rules across analysis passes.
package sourcepolicy

import "strings"

var generatedMarkers = []string{
	"Code generated by",
	"@generated",
	"DO NOT EDIT",
	"autogenerated by",
	"This file was automatically generated",
	"AUTOGENERATED FILE",
}

// Generated recognizes leading generator markers. Limiting the scan to eight
// lines prevents a later comment quoting a marker from suppressing analysis.
func Generated(content string) bool {
	for i, line := range strings.SplitN(content, "\n", 9) {
		if i >= 8 {
			break
		}
		for _, marker := range generatedMarkers {
			if strings.Contains(line, marker) {
				return true
			}
		}
	}
	return false
}
