package prompt

import (
	"fmt"
	"strings"

	"github.com/jdziat/open-nitpick/internal/config"
)

// LayerPersona is the layer name for voice and scope instructions.
const LayerPersona = "persona"

// Persona renders a configured persona as prompt text.
//
// Two rules govern everything here. First, each instruction is phrased as a
// concrete behavior rather than an adjective: "one sentence of rationale" is
// followable, "be terse" is not, and models comply with the former far more
// reliably. Second, voice instructions never soften the *bar* for reporting —
// a warm reviewer and a blunt one must find the same defects and differ only in
// wording, or the tone knob silently becomes a quality knob.
func Persona(p config.Persona) string {
	var b strings.Builder

	b.WriteString("## Voice and scope\n\n")

	// Always the generation scope. The configured nitpick level is applied
	// afterwards as a filter over classes, so a narrower level never changes
	// what the model was asked to look for.
	b.WriteString(nitpickScope(config.GenerationLevel))
	b.WriteString("\n")
	b.WriteString(voice(p))

	if custom := strings.TrimSpace(p.Custom); custom != "" {
		b.WriteString("\nAdditional house style, which overrides the wording guidance above ")
		b.WriteString("but never the reporting bar:\n\n")
		b.WriteString(custom)
		b.WriteString("\n")
	}

	return b.String()
}

// StylePass renders the prompt for the separate style review.
//
// Style is generated by its own pass rather than by widening the main one.
// Across four eval runs, asking one pass to do both consistently produced more
// findings, lower precision, and more missed real defects: attention spent on
// naming is attention not spent on the race condition. Splitting them keeps the
// defect hunt undiluted and makes the style findings independently droppable.
func StylePass(p config.Persona) string {
	var b strings.Builder

	b.WriteString("## Voice and scope\n\n")
	b.WriteString("Report ONLY naming, documentation, structure, idiom, and consistency " +
		"observations. Another reviewer is separately handling correctness, security, " +
		"concurrency, resources, and tests — do not duplicate that work, and do not " +
		"report anything from those categories here.\n\n" +
		"Set `class` to \"style\" and `severity` to \"nit\" on every finding.\n\n" +
		"Still say what each one costs a future reader. A nit with no stated cost is " +
		"noise, and this pass exists to be useful rather than exhaustive. Do not report " +
		"anything a formatter or linter already enforces. An empty findings list is a " +
		"perfectly good answer.\n")
	b.WriteString(voice(p))

	if custom := strings.TrimSpace(p.Custom); custom != "" {
		b.WriteString("\nAdditional house style:\n\n" + custom + "\n")
	}

	return b.String()
}

// nitpickScope describes which categories are in scope.
//
// Scope is stated as an inclusion list plus an explicit exclusion list. Models
// are markedly better at "report X, Y, Z and nothing else" than at calibrating
// a vague threshold, and the exclusions are what actually keep the output
// scannable.
func nitpickScope(level config.NitpickLevel) string {
	const core = "correctness, concurrency, security, resource handling, and data loss"

	switch level {
	case config.NitpickOff:
		return "Report ONLY defects in " + core + " — problems where you can name an " +
			"input or sequence that produces a wrong result, a crash, a leak, or a breach.\n\n" +
			"Do NOT report: missing tests, API or contract changes, naming, documentation, " +
			"structure, idiom, or style. If the change contains no defect of the kinds listed " +
			"above, return an empty findings list. That is the expected outcome for most changes.\n"

	case config.NitpickMinimal:
		return "Report defects in " + core + ", plus changes that break an existing caller " +
			"or published contract.\n\n" +
			"Do NOT report: missing tests, naming, documentation, structure, idiom, or style. " +
			"An empty findings list is the expected outcome for most changes.\n"

	case config.NitpickPedantic:
		return "Report defects in " + core + ", contract breakage, and missing tests for new " +
			"branching logic.\n\n" +
			"You may ALSO report naming, documentation, structure, idiom, and consistency " +
			"observations — this repository has asked for them. Mark every such finding `nit`, " +
			"and still say what it costs a future reader. A nit with no stated cost is noise " +
			"even here.\n\n" +
			"Do not report anything a formatter or linter already enforces.\n"

	default: // normal
		return "Report defects in " + core + ", contract breakage, and missing tests where new " +
			"branching logic is genuinely risky.\n\n" +
			// THE EXAMPLE USED TO BE A CORRECTNESS BUG. It read "not 'this is
			// complex', but 'this shadows err, so the outer error is silently
			// discarded'" — and an error being silently discarded is not a
			// maintainability cost, it is something going wrong. It is the only
			// example given for what "concretely" means, so it set the bar for
			// reporting a maintainability problem at the warning definition:
			// "likely a bug, or a genuine hazard under plausible conditions".
			//
			// The replacement is duplication rather than either of the two
			// illustrations the severity ladder carried at the time, and
			// deliberately: those were "widening an exported type's accepted input"
			// and "adding a dependency for one helper function", which are two of
			// the three maintainability plants in the eval corpus stated almost
			// verbatim. Repeating them here would tune the prompt to the corpus.
			// Duplication costs a future change and matches nothing planted.
			//
			// Both of those ladder illustrations have since been replaced, because
			// naming a planted defect three lines above "do not go looking for
			// them" measured 0 of 3 on each — and because the sentence was false
			// for a user with no corpus at all. See review.md's `info` rung and
			// internal/evals/promptcollision_test.go, which is now the guard
			// against a prompt example naming what the corpus plants.
			//
			// THE CHANGE BOUGHT NOTHING MEASURABLE AND IS KEPT ONLY BECAUSE THE OLD
			// EXAMPLE WAS WRONG. Measured, kimi-k3, three runs over each of the five
			// info fixtures, before and after: 3 of 15 both times, every hit the
			// security plant, and the three maintainability plants 0 of 9 under both
			// wordings. The prediction was that the mis-anchored example suppressed
			// them and that correcting it would move go-package-singleton, which was
			// then the one maintainability plant the severity ladder did not name. It
			// did not move.
			//
			// THAT CONTROL NO LONGER EXISTS, and the number above was taken while it
			// did. review.md's ladder has since been rewritten and now names none of
			// the three maintainability plants, so nothing separates
			// go-package-singleton from its two neighbours any more. Re-running the
			// comparison would measure a different ladder; the 3-of-15 stands as a
			// record of what was measured, not as a claim about the prompt that ships
			// today. A first version of this also added "nothing has to go wrong for
			// it to be worth raising", which lowers the reporting bar; that sentence
			// was removed rather than kept, because the measurement that was meant
			// to justify it came back flat and invented findings went 1 to 2 over
			// the same 15 reviews. Loosening a bar on a prediction the numbers did
			// not support is how a prompt acquires noise it cannot account for.
			"You may report a maintainability problem only when you can name what it will cost " +
			"concretely — not \"this is complex\", but \"this is the third place the retry policy " +
			"is written, so the next change to it has three sites to find\".\n\n" +
			"Do NOT report: naming preferences, documentation wording, formatting, import order, " +
			"or anything a formatter or linter already enforces. An empty findings list is a " +
			"common and correct outcome.\n"
	}
}

// ScopeText renders the scope instructions for one nitpick level.
//
// Persona always renders GenerationLevel, so the text of the other three
// branches is unreachable from outside this package. It is exported for the
// guard in internal/evals that scans the shipped words for eval-corpus
// keywords: a branch that nothing renders today still ships the day
// GenerationLevel moves, and a guard that could only see today's branch would
// not notice the collision until then.
func ScopeText(level config.NitpickLevel) string { return nitpickScope(level) }

// voice renders the wording axes.
func voice(p config.Persona) string {
	var b strings.Builder

	b.WriteString("\nWrite each finding like this:\n\n")

	switch p.Verbosity {
	case config.VerbosityTerse:
		b.WriteString("- `title`: under 10 words, naming the defect.\n")
		b.WriteString("- `rationale`: ONE sentence stating the consequence. No restatement of the code, no preamble.\n")
	case config.VerbosityDetailed:
		b.WriteString("- `title`: one line naming the defect.\n")
		b.WriteString("- `rationale`: three to five sentences: the consequence, the sequence that triggers it, " +
			"and what to do instead. Still no restatement of what the code plainly says.\n")
	default:
		b.WriteString("- `title`: one line naming the defect.\n")
		b.WriteString("- `rationale`: one to three sentences giving the consequence and the reasoning. " +
			"Do not restate the code.\n")
	}

	switch p.Politeness {
	case config.PolitenessBlunt:
		b.WriteString("- Tone: state the problem directly. No softeners (\"consider\", \"perhaps\", " +
			"\"it might be worth\"), no acknowledgements, no closing pleasantries.\n")
	case config.PolitenessWarm:
		b.WriteString("- Tone: collegial. Acknowledge the intent of the change where it is clear, and " +
			"frame findings as recommendations a colleague is offering. Never sarcastic, never " +
			"condescending. Warmth must not blunt the finding: say plainly what is wrong.\n")
	default:
		b.WriteString("- Tone: plain and professional. No softeners, no flattery, no apologies.\n")
	}

	switch p.Confidence {
	case config.ConfidenceHedged:
		b.WriteString("- Certainty: distinguish what you verified from what you inferred. When a " +
			"conclusion depends on code you were not shown, say so in the rationale " +
			"(\"if Close is not idempotent, this double-frees\").\n")
	default:
		b.WriteString("- Certainty: assert findings you are confident in plainly, without hedging. " +
			"If you are NOT confident, either omit the finding or state the specific assumption " +
			"it rests on — do not pad an uncertain claim with vague qualifiers.\n")
	}

	switch p.Address {
	case config.AddressAuthor:
		b.WriteString("- Address the author as \"you\".\n")
	default:
		b.WriteString("- Describe the code, not the author. Do not use \"you\" or \"your\".\n")
	}

	if p.PraiseEnabled() {
		b.WriteString("- You may note genuinely good decisions, at most once per review, and only " +
			"when the decision is non-obvious. Never praise ordinary correct code.\n")
	} else {
		b.WriteString("- Do not praise, compliment, or summarize what the change does well.\n")
	}

	return b.String()
}

// Describe summarizes a persona in one line, for `explain-config`.
func Describe(p config.Persona) string {
	return fmt.Sprintf("verbosity=%s politeness=%s confidence=%s nitpick=%s address=%s emoji=%t praise=%t",
		p.Verbosity, p.Politeness, p.Confidence, p.Nitpick, p.Address, p.EmojiEnabled(), p.PraiseEnabled())
}
