package prflow

import (
	"context"
	"reflect"
	"testing"

	"github.com/jdziat/open-nitpick/internal/diff"
)

func TestMaterializeStopsReadingWhenBytesAreExhausted(t *testing.T) {
	for _, unchanged := range []bool{false, true} {
		t.Run(map[bool]string{false: "changed", true: "unchanged"}[unchanged], func(t *testing.T) {
			source := &budgetSource{treeSource: treeSource{files: map[string][]byte{
				"a.go": []byte("package p\n"), "b.go": []byte("package p\n"), "c.go": []byte("package p\n"),
			}}}
			changes := diff.Files{&diff.File{Path: "a.go"}}
			if !unchanged {
				changes = append(changes, &diff.File{Path: "b.go"}, &diff.File{Path: "c.go"})
			}
			files, omissions, err := materialize(context.Background(), Request{Changes: changes, Source: source}, Options{MaxBytes: 20, MaxFiles: 10, IncludeUnchanged: unchanged})
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(source.reads, []string{"a.go", "b.go"}) || len(files) != 2 || !hasOmission(omissions, "max_bytes") {
				t.Fatalf("reads=%v files=%v omissions=%v; want two reads and an explicit byte limit", source.reads, files, omissions)
			}
		})
	}
}

func TestMaterializeAppliesLimitsInStablePathOrder(t *testing.T) {
	source := []SourceFile{{Path: "z.go", Content: []byte("package z\n")}, {Path: "a.go", Content: []byte("package a\n")}}
	files, omissions, err := materialize(context.Background(), Request{Files: source}, Options{MaxBytes: 10, MaxFiles: 2})
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || files[0].Path != "a.go" || !hasOmission(omissions, "max_bytes") {
		t.Fatalf("files=%v omissions=%v, want a.go retained", files, omissions)
	}
	files[0].Content[0] = 'x'
	if string(source[1].Content) != "package a\n" {
		t.Fatal("materialized source aliases its caller")
	}
}

func TestMaterializeCancellationPreventsSourceReads(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	source := &budgetSource{treeSource: treeSource{files: map[string][]byte{"a.go": []byte("package p\n")}}}
	_, omissions, _ := materialize(ctx, Request{Changes: diff.Files{&diff.File{Path: "a.go"}}, Source: source}, Options{MaxBytes: 10, MaxFiles: 1})
	if len(source.reads) != 0 || !hasOmission(omissions, "timeout") {
		t.Fatalf("reads=%v omissions=%v, want cancellation before read", source.reads, omissions)
	}
}

func TestMaterializeExcludesGeneratedContextWithinReadBudget(t *testing.T) {
	generated := []byte("// Code generated by probe. DO NOT EDIT.\npackage p\n")
	source := &budgetSource{treeSource: treeSource{files: map[string][]byte{
		"a.go": generated, "b.go": generated, "c.go": []byte("package p\n"),
	}}}
	files, omissions, err := materialize(context.Background(), Request{Source: source}, Options{MaxFiles: 10, MaxBytes: 2 * len(generated), IncludeUnchanged: true, SkipGenerated: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 0 || !reflect.DeepEqual(source.reads, []string{"a.go", "b.go"}) || !hasOmission(omissions, "generated_file") || !hasOmission(omissions, "max_bytes") {
		t.Fatalf("files=%v reads=%v omissions=%v; generated context must be excluded and spend the read budget", files, source.reads, omissions)
	}
}

func TestMaterializeSelectsSourceForExplicitUnchangedEntrypoint(t *testing.T) {
	source := &treeSource{files: map[string][]byte{"p.go": []byte("package p\nfunc Entry(){}\n")}}
	files, _, err := materialize(context.Background(), Request{Source: source}, Options{MaxFiles: 10, MaxBytes: 1024, Entrypoints: []string{"p.Entry"}})
	if err != nil || len(files) != 1 || files[0].Path != "p.go" {
		t.Fatalf("explicit entrypoint source = %+v, err=%v", files, err)
	}
}

type budgetSource struct {
	treeSource
	reads []string
}

func (s *budgetSource) ReadFile(ctx context.Context, revision Revision, name string) ([]byte, error) {
	s.reads = append(s.reads, name)
	return s.treeSource.ReadFile(ctx, revision, name)
}
